[package]
name = "ekubo_limit_order"
version = "0.1.0"
cairo-version = "2.5.3"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "=2.5.3"
ekubo = { git = "https://github.com/EkuboProtocol/abis.git" }
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[lib]
allowed-libfuncs-list.name = "experimental"